INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES(10001, 'in28minutes', 'GET AWS CERTIFIED', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES(10002, 'in28minutes', 'GET AZURE CERTIFIED', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES(10003, 'in28minutes', 'Learn Fullstack Dev', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES(10004, 'in28minutes', 'Learn DevOps 1', CURRENT_DATE(), false);
